# Generated by Django 4.2.6 on 2023-10-29 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BeneficiarioCalentador',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('folio_mids', models.CharField(max_length=255)),
                ('apellido_paterno', models.CharField(max_length=100)),
                ('apellido_materno', models.CharField(blank=True, max_length=100, null=True)),
                ('nombres', models.CharField(max_length=100)),
                ('municipio', models.CharField(max_length=150)),
                ('localidad', models.CharField(max_length=150)),
            ],
        ),
    ]
