# Generated by Django 4.2.7 on 2023-11-19 20:43

import beneficiarios.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiarios', '0002_alter_beneficiariocalentador_municipio'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiariocalentador',
            name='finalizado',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='EvidenciasCalentadores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to=beneficiarios.models.upload_to_directory)),
                ('es_proceso', models.BooleanField(default=True)),
                ('beneficiario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beneficiarios.beneficiariocalentador')),
            ],
        ),
    ]
