version: '3.3'

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env  # Cargar las variables desde el archivo .env
    depends_on:
      - db

  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}  # Variable tomada de .env
      MYSQL_DATABASE: ${DB_NAME}               # Variable tomada de .env
      MYSQL_USER: ${DB_USER}                   # Variable tomada de .env
      MYSQL_PASSWORD: ${DB_PASSWORD}           # Variable tomada de .env
    ports:
      - "3320:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:  