# Generated by Django 4.2.5 on 2023-10-10 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficiario_Calentador',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('folio_mids', models.CharField(max_length=255)),
                ('apellido_paterno', models.CharField(max_length=255)),
                ('apellido_materno', models.CharField(blank=True, max_length=255, null=True)),
                ('nombres', models.CharField(max_length=255)),
                ('municipio', models.CharField(max_length=255)),
                ('localidad', models.CharField(max_length=255)),
            ],
        ),
    ]
