# Generated by Django 4.2.5 on 2023-10-18 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficiarios_Calentadores',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('folio_mids', models.CharField(max_length=255)),
                ('apellido_paterno', models.CharField(max_length=100)),
                ('apellido_materno', models.CharField(blank=True, max_length=100, null=True)),
                ('nombres', models.CharField(max_length=100)),
                ('municipio', models.CharField(max_length=150)),
                ('localidad', models.CharField(max_length=150)),
            ],
        ),
        migrations.DeleteModel(
            name='Beneficiario_Calentador',
        ),
    ]
