# Generated by Django 4.2.7 on 2023-11-28 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('obras', '0002_alter_obrapublica_municipio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evidenciasobraspublicas',
            old_name='beneficiario',
            new_name='obra',
        ),
    ]
